// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAp0IGOIUc-33Ldm1K4p4IAjEVcttHH8YE',
    appId: '1:658067713438:web:242ff3d831b84e0b84fa8f',
    messagingSenderId: '658067713438',
    projectId: 'treasury-movement-sm',
    authDomain: 'treasury-movement-sm.firebaseapp.com',
    storageBucket: 'treasury-movement-sm.firebasestorage.app',
    measurementId: 'G-S2MDG5WCYJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5qg1CYAlf5G72ptQ1gUc-z_vPjULE3PU',
    appId: '1:658067713438:android:43ae8a87b67565a284fa8f',
    messagingSenderId: '658067713438',
    projectId: 'treasury-movement-sm',
    storageBucket: 'treasury-movement-sm.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGU7LIaTfdWBcoIT-4Srjb403TtSsw3T4',
    appId: '1:658067713438:ios:14d00f57f3f4061684fa8f',
    messagingSenderId: '658067713438',
    projectId: 'treasury-movement-sm',
    storageBucket: 'treasury-movement-sm.firebasestorage.app',
    iosBundleId: 'com.example.treasuryMovementSm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGU7LIaTfdWBcoIT-4Srjb403TtSsw3T4',
    appId: '1:658067713438:ios:14d00f57f3f4061684fa8f',
    messagingSenderId: '658067713438',
    projectId: 'treasury-movement-sm',
    storageBucket: 'treasury-movement-sm.firebasestorage.app',
    iosBundleId: 'com.example.treasuryMovementSm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAp0IGOIUc-33Ldm1K4p4IAjEVcttHH8YE',
    appId: '1:658067713438:web:f8b2295d06ae06de84fa8f',
    messagingSenderId: '658067713438',
    projectId: 'treasury-movement-sm',
    authDomain: 'treasury-movement-sm.firebaseapp.com',
    storageBucket: 'treasury-movement-sm.firebasestorage.app',
    measurementId: 'G-FRLKCR82LZ',
  );
}
